// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uexecutor/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParams struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgExecutePayload defines a message for executing a universal payload
type MsgExecutePayload struct {
	// signer is the Cosmos address initiating the tx (used for tx signing)
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// universal_account_id is the identifier of the owner account
	UniversalAccountId *UniversalAccountId `protobuf:"bytes,2,opt,name=universal_account_id,json=universalAccountId,proto3" json:"universal_account_id,omitempty"`
	// payload is the universal payload to be executed
	UniversalPayload *UniversalPayload `protobuf:"bytes,3,opt,name=universal_payload,json=universalPayload,proto3" json:"universal_payload,omitempty"`
	// verification_data is the bytes passed as verifier data for the given payload.
	VerificationData string `protobuf:"bytes,4,opt,name=verification_data,json=verificationData,proto3" json:"verification_data,omitempty"`
}

func (m *MsgExecutePayload) Reset()         { *m = MsgExecutePayload{} }
func (m *MsgExecutePayload) String() string { return proto.CompactTextString(m) }
func (*MsgExecutePayload) ProtoMessage()    {}
func (*MsgExecutePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{2}
}
func (m *MsgExecutePayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecutePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecutePayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecutePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecutePayload.Merge(m, src)
}
func (m *MsgExecutePayload) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecutePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecutePayload.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecutePayload proto.InternalMessageInfo

func (m *MsgExecutePayload) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgExecutePayload) GetUniversalAccountId() *UniversalAccountId {
	if m != nil {
		return m.UniversalAccountId
	}
	return nil
}

func (m *MsgExecutePayload) GetUniversalPayload() *UniversalPayload {
	if m != nil {
		return m.UniversalPayload
	}
	return nil
}

func (m *MsgExecutePayload) GetVerificationData() string {
	if m != nil {
		return m.VerificationData
	}
	return ""
}

// MsgExecutePayloadResponse defines the response for MsgExecutePayload.
type MsgExecutePayloadResponse struct {
}

func (m *MsgExecutePayloadResponse) Reset()         { *m = MsgExecutePayloadResponse{} }
func (m *MsgExecutePayloadResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecutePayloadResponse) ProtoMessage()    {}
func (*MsgExecutePayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{3}
}
func (m *MsgExecutePayloadResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecutePayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecutePayloadResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecutePayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecutePayloadResponse.Merge(m, src)
}
func (m *MsgExecutePayloadResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecutePayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecutePayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecutePayloadResponse proto.InternalMessageInfo

// MsgMigrateUEA defines a message for migarting Universal Executor Account (UEA)
type MsgMigrateUEA struct {
	// signer is the Cosmos address initiating the tx (used for tx signing)
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// universal_account_id is the identifier of the owner account
	UniversalAccountId *UniversalAccountId `protobuf:"bytes,2,opt,name=universal_account_id,json=universalAccountId,proto3" json:"universal_account_id,omitempty"`
	// payload is the migration payload to be executed
	MigrationPayload *MigrationPayload `protobuf:"bytes,3,opt,name=migration_payload,json=migrationPayload,proto3" json:"migration_payload,omitempty"`
	// signature is the bytes passed as verifier data for the given payload.
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgMigrateUEA) Reset()         { *m = MsgMigrateUEA{} }
func (m *MsgMigrateUEA) String() string { return proto.CompactTextString(m) }
func (*MsgMigrateUEA) ProtoMessage()    {}
func (*MsgMigrateUEA) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{4}
}
func (m *MsgMigrateUEA) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrateUEA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrateUEA.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrateUEA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrateUEA.Merge(m, src)
}
func (m *MsgMigrateUEA) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrateUEA) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrateUEA.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrateUEA proto.InternalMessageInfo

func (m *MsgMigrateUEA) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgMigrateUEA) GetUniversalAccountId() *UniversalAccountId {
	if m != nil {
		return m.UniversalAccountId
	}
	return nil
}

func (m *MsgMigrateUEA) GetMigrationPayload() *MigrationPayload {
	if m != nil {
		return m.MigrationPayload
	}
	return nil
}

func (m *MsgMigrateUEA) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// MsgMigrateUEAResponse defines the response for MsgMigrateUEA.
type MsgMigrateUEAResponse struct {
}

func (m *MsgMigrateUEAResponse) Reset()         { *m = MsgMigrateUEAResponse{} }
func (m *MsgMigrateUEAResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMigrateUEAResponse) ProtoMessage()    {}
func (*MsgMigrateUEAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{5}
}
func (m *MsgMigrateUEAResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMigrateUEAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMigrateUEAResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMigrateUEAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMigrateUEAResponse.Merge(m, src)
}
func (m *MsgMigrateUEAResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMigrateUEAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMigrateUEAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMigrateUEAResponse proto.InternalMessageInfo

// MsgVoteInbound allows a universal validator to vote on an inbound transfer.
type MsgVoteInbound struct {
	// signer is the Cosmos address initiating the tx (used for tx signing)
	Signer  string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Inbound *Inbound `protobuf:"bytes,2,opt,name=inbound,proto3" json:"inbound,omitempty"`
}

func (m *MsgVoteInbound) Reset()         { *m = MsgVoteInbound{} }
func (m *MsgVoteInbound) String() string { return proto.CompactTextString(m) }
func (*MsgVoteInbound) ProtoMessage()    {}
func (*MsgVoteInbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{6}
}
func (m *MsgVoteInbound) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteInbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteInbound.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteInbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteInbound.Merge(m, src)
}
func (m *MsgVoteInbound) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteInbound) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteInbound.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteInbound proto.InternalMessageInfo

func (m *MsgVoteInbound) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgVoteInbound) GetInbound() *Inbound {
	if m != nil {
		return m.Inbound
	}
	return nil
}

// MsgVoteInboundResponse defines the response for MsgExecutePayload.
type MsgVoteInboundResponse struct {
}

func (m *MsgVoteInboundResponse) Reset()         { *m = MsgVoteInboundResponse{} }
func (m *MsgVoteInboundResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVoteInboundResponse) ProtoMessage()    {}
func (*MsgVoteInboundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{7}
}
func (m *MsgVoteInboundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteInboundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteInboundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteInboundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteInboundResponse.Merge(m, src)
}
func (m *MsgVoteInboundResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteInboundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteInboundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteInboundResponse proto.InternalMessageInfo

// MsgVoteOutbound allows a universal validator to vote on an outbound tx observation.
type MsgVoteOutbound struct {
	// signer is the Cosmos address initiating the tx (used for tx signing)
	Signer     string               `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	TxId       string               `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UtxId      string               `protobuf:"bytes,3,opt,name=utx_id,json=utxId,proto3" json:"utx_id,omitempty"`
	ObservedTx *OutboundObservation `protobuf:"bytes,4,opt,name=observed_tx,json=observedTx,proto3" json:"observed_tx,omitempty"`
}

func (m *MsgVoteOutbound) Reset()         { *m = MsgVoteOutbound{} }
func (m *MsgVoteOutbound) String() string { return proto.CompactTextString(m) }
func (*MsgVoteOutbound) ProtoMessage()    {}
func (*MsgVoteOutbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{8}
}
func (m *MsgVoteOutbound) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteOutbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteOutbound.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteOutbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteOutbound.Merge(m, src)
}
func (m *MsgVoteOutbound) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteOutbound) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteOutbound.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteOutbound proto.InternalMessageInfo

func (m *MsgVoteOutbound) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgVoteOutbound) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *MsgVoteOutbound) GetUtxId() string {
	if m != nil {
		return m.UtxId
	}
	return ""
}

func (m *MsgVoteOutbound) GetObservedTx() *OutboundObservation {
	if m != nil {
		return m.ObservedTx
	}
	return nil
}

// MsgVoteInboundResponse defines the response for MsgExecutePayload.
type MsgVoteOutboundResponse struct {
}

func (m *MsgVoteOutboundResponse) Reset()         { *m = MsgVoteOutboundResponse{} }
func (m *MsgVoteOutboundResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVoteOutboundResponse) ProtoMessage()    {}
func (*MsgVoteOutboundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{9}
}
func (m *MsgVoteOutboundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteOutboundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteOutboundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteOutboundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteOutboundResponse.Merge(m, src)
}
func (m *MsgVoteOutboundResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteOutboundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteOutboundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteOutboundResponse proto.InternalMessageInfo

// MsgVoteChainMeta is broadcasted by Universal Validators to submit observed chain metadata (gas price + block height)
type MsgVoteChainMeta struct {
	Signer          string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	ObservedChainId string `protobuf:"bytes,2,opt,name=observed_chain_id,json=observedChainId,proto3" json:"observed_chain_id,omitempty"`
	Price           uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ChainHeight     uint64 `protobuf:"varint,4,opt,name=chain_height,json=chainHeight,proto3" json:"chain_height,omitempty"`
}

func (m *MsgVoteChainMeta) Reset()         { *m = MsgVoteChainMeta{} }
func (m *MsgVoteChainMeta) String() string { return proto.CompactTextString(m) }
func (*MsgVoteChainMeta) ProtoMessage()    {}
func (*MsgVoteChainMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{10}
}
func (m *MsgVoteChainMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteChainMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteChainMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteChainMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteChainMeta.Merge(m, src)
}
func (m *MsgVoteChainMeta) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteChainMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteChainMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteChainMeta proto.InternalMessageInfo

func (m *MsgVoteChainMeta) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgVoteChainMeta) GetObservedChainId() string {
	if m != nil {
		return m.ObservedChainId
	}
	return ""
}

func (m *MsgVoteChainMeta) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MsgVoteChainMeta) GetChainHeight() uint64 {
	if m != nil {
		return m.ChainHeight
	}
	return 0
}

// MsgVoteChainMetaResponse defines the response for MsgVoteChainMeta
type MsgVoteChainMetaResponse struct {
}

func (m *MsgVoteChainMetaResponse) Reset()         { *m = MsgVoteChainMetaResponse{} }
func (m *MsgVoteChainMetaResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVoteChainMetaResponse) ProtoMessage()    {}
func (*MsgVoteChainMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d6216044506365, []int{11}
}
func (m *MsgVoteChainMetaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteChainMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteChainMetaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteChainMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteChainMetaResponse.Merge(m, src)
}
func (m *MsgVoteChainMetaResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteChainMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteChainMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteChainMetaResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "uexecutor.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "uexecutor.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgExecutePayload)(nil), "uexecutor.v1.MsgExecutePayload")
	proto.RegisterType((*MsgExecutePayloadResponse)(nil), "uexecutor.v1.MsgExecutePayloadResponse")
	proto.RegisterType((*MsgMigrateUEA)(nil), "uexecutor.v1.MsgMigrateUEA")
	proto.RegisterType((*MsgMigrateUEAResponse)(nil), "uexecutor.v1.MsgMigrateUEAResponse")
	proto.RegisterType((*MsgVoteInbound)(nil), "uexecutor.v1.MsgVoteInbound")
	proto.RegisterType((*MsgVoteInboundResponse)(nil), "uexecutor.v1.MsgVoteInboundResponse")
	proto.RegisterType((*MsgVoteOutbound)(nil), "uexecutor.v1.MsgVoteOutbound")
	proto.RegisterType((*MsgVoteOutboundResponse)(nil), "uexecutor.v1.MsgVoteOutboundResponse")
	proto.RegisterType((*MsgVoteChainMeta)(nil), "uexecutor.v1.MsgVoteChainMeta")
	proto.RegisterType((*MsgVoteChainMetaResponse)(nil), "uexecutor.v1.MsgVoteChainMetaResponse")
}

func init() { proto.RegisterFile("uexecutor/v1/tx.proto", fileDescriptor_88d6216044506365) }

var fileDescriptor_88d6216044506365 = []byte{
	// 860 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0xe3, 0x54,
	0x14, 0xad, 0xdb, 0xb4, 0xa8, 0x37, 0x9d, 0x99, 0xc6, 0x24, 0xc4, 0x71, 0xa7, 0x9e, 0x36, 0x7c,
	0xcc, 0x90, 0xa1, 0x31, 0x13, 0xa4, 0x59, 0x64, 0xd7, 0xc0, 0x48, 0x44, 0xc8, 0x4c, 0x31, 0x2d,
	0x48, 0xb3, 0x89, 0x5e, 0xec, 0x87, 0x63, 0x69, 0xec, 0x67, 0xf9, 0x3d, 0x47, 0xe9, 0x0e, 0xb1,
	0x64, 0x35, 0x2b, 0xfe, 0x03, 0x62, 0xd3, 0x05, 0x3f, 0x80, 0xe5, 0x2c, 0x47, 0x48, 0x48, 0xac,
	0x46, 0xa8, 0x5d, 0xf4, 0x6f, 0x20, 0x3f, 0x7f, 0xe5, 0x39, 0x21, 0x95, 0xba, 0x62, 0x53, 0xbd,
	0x9c, 0x73, 0xef, 0xe9, 0x3d, 0xc7, 0xcf, 0x37, 0x81, 0x46, 0x84, 0x67, 0xd8, 0x8a, 0x18, 0x09,
	0xf5, 0xe9, 0x13, 0x9d, 0xcd, 0xba, 0x41, 0x48, 0x18, 0x91, 0x77, 0x72, 0xb8, 0x3b, 0x7d, 0xa2,
	0xd6, 0x90, 0xe7, 0xfa, 0x44, 0xe7, 0x7f, 0x93, 0x02, 0xb5, 0x69, 0x11, 0xea, 0x11, 0xaa, 0x7b,
	0xd4, 0x89, 0x1b, 0x3d, 0xea, 0xa4, 0x84, 0x22, 0x0a, 0x9e, 0x07, 0x98, 0xa6, 0xcc, 0xbe, 0xc0,
	0x58, 0x13, 0xe4, 0xfa, 0x23, 0x0f, 0x33, 0x94, 0xd2, 0x75, 0x87, 0x38, 0x84, 0x1f, 0xf5, 0xf8,
	0x94, 0xa2, 0xad, 0xe4, 0xff, 0x8c, 0x12, 0x22, 0xf9, 0x90, 0x50, 0xed, 0xdf, 0x24, 0xb8, 0x67,
	0x50, 0xe7, 0x2c, 0xb0, 0x11, 0xc3, 0x27, 0x28, 0x44, 0x1e, 0x95, 0x9f, 0xc2, 0x36, 0x8a, 0xd8,
	0x84, 0x84, 0x2e, 0x3b, 0x57, 0xa4, 0x03, 0xe9, 0xd1, 0xf6, 0x40, 0xf9, 0xf3, 0xf7, 0xa3, 0x7a,
	0xda, 0x78, 0x6c, 0xdb, 0x21, 0xa6, 0xf4, 0x5b, 0x16, 0xba, 0xbe, 0x63, 0x16, 0xa5, 0x72, 0x0f,
	0xb6, 0x02, 0xae, 0xa0, 0xac, 0x1f, 0x48, 0x8f, 0xaa, 0xbd, 0x7a, 0x77, 0x3e, 0x80, 0x6e, 0xa2,
	0x3e, 0xa8, 0xbc, 0x7e, 0xfb, 0x60, 0xcd, 0x4c, 0x2b, 0xfb, 0x9f, 0xfc, 0x74, 0x7d, 0xd1, 0x29,
	0x34, 0x7e, 0xbe, 0xbe, 0xe8, 0xb4, 0x0a, 0x8b, 0xa5, 0xc9, 0xda, 0x2d, 0x68, 0x96, 0x20, 0x13,
	0xd3, 0x80, 0xf8, 0x14, 0xb7, 0xff, 0x58, 0x87, 0x9a, 0x41, 0x9d, 0x67, 0xbc, 0x15, 0x9f, 0xa0,
	0xf3, 0x97, 0x04, 0xd9, 0xf2, 0xa7, 0xb0, 0x45, 0x5d, 0xc7, 0xc7, 0xe1, 0x8d, 0x3e, 0xd2, 0x3a,
	0xd9, 0x84, 0x7a, 0xe4, 0xbb, 0x53, 0x1c, 0x52, 0xf4, 0x72, 0x84, 0x2c, 0x8b, 0x44, 0x3e, 0x1b,
	0xb9, 0x76, 0x6a, 0xe9, 0x40, 0xb4, 0x74, 0x96, 0x55, 0x1e, 0x27, 0x85, 0x43, 0xdb, 0x94, 0xa3,
	0x05, 0x4c, 0xfe, 0x0a, 0x6a, 0x85, 0x66, 0x90, 0x8c, 0xa6, 0x6c, 0x70, 0x41, 0xed, 0x3f, 0x04,
	0x53, 0x03, 0xe6, 0x6e, 0x54, 0x42, 0xe4, 0xc7, 0x50, 0x9b, 0xe2, 0xd0, 0xfd, 0xc1, 0xb5, 0x10,
	0x73, 0x89, 0x3f, 0xb2, 0x11, 0x43, 0x4a, 0x25, 0x76, 0x67, 0xee, 0xce, 0x13, 0x5f, 0x20, 0x86,
	0xfa, 0x8f, 0xe3, 0x78, 0x53, 0x6b, 0x71, 0xb6, 0x7b, 0x42, 0xb6, 0x62, 0x58, 0xed, 0x3d, 0x68,
	0x2d, 0x80, 0x79, 0xbe, 0xbf, 0xae, 0xc3, 0x1d, 0x83, 0x3a, 0x86, 0xeb, 0x84, 0x88, 0xe1, 0xb3,
	0x67, 0xc7, 0xff, 0x9f, 0x6c, 0x3d, 0x3e, 0x53, 0x9c, 0xc5, 0xca, 0x6c, 0x8d, 0xac, 0x2c, 0xcf,
	0xd6, 0x2b, 0x21, 0xf2, 0x7d, 0xd8, 0x8e, 0x47, 0x45, 0x2c, 0x0a, 0x71, 0x9a, 0x69, 0x01, 0xf4,
	0x1f, 0x96, 0xc2, 0x6c, 0x0a, 0x61, 0x16, 0xc9, 0xb4, 0x9b, 0xd0, 0x10, 0x80, 0x3c, 0xc4, 0x5f,
	0x24, 0xb8, 0x6b, 0x50, 0xe7, 0x3b, 0xc2, 0xf0, 0xd0, 0x1f, 0x93, 0xc8, 0xbf, 0xcd, 0x0d, 0xd5,
	0xe1, 0x1d, 0x37, 0x69, 0x4e, 0x83, 0x6b, 0x88, 0x3e, 0x53, 0x65, 0x33, 0xab, 0xea, 0x1f, 0x96,
	0xe6, 0xae, 0x45, 0x58, 0x17, 0xa7, 0x68, 0x2b, 0xf0, 0x9e, 0x88, 0xe4, 0x23, 0xbf, 0x4d, 0x16,
	0x44, 0x4c, 0x3d, 0x8f, 0xd8, 0x6d, 0x67, 0x7e, 0x17, 0x36, 0xd9, 0x2c, 0x7b, 0xd4, 0xdb, 0x66,
	0x85, 0xcd, 0x86, 0xb6, 0xdc, 0x80, 0xad, 0x28, 0x41, 0x37, 0x38, 0xba, 0x19, 0x71, 0x78, 0x00,
	0x55, 0x32, 0xa6, 0x38, 0x9c, 0x62, 0x7b, 0xc4, 0x66, 0xfc, 0x31, 0x54, 0x7b, 0x87, 0xa2, 0xc7,
	0x6c, 0x94, 0xe7, 0xbc, 0x90, 0x3f, 0x43, 0x13, 0xb2, 0xae, 0xd3, 0x59, 0xff, 0xe3, 0x92, 0x65,
	0x71, 0xa7, 0xcc, 0x9b, 0x49, 0x77, 0xca, 0x3c, 0x94, 0x7b, 0xff, 0x4b, 0x82, 0xdd, 0x94, 0xfb,
	0x3c, 0xde, 0xb4, 0x06, 0x66, 0xe8, 0x16, 0xe6, 0x3b, 0x50, 0xcb, 0x0d, 0x25, 0x1b, 0x3b, 0x0f,
	0xe2, 0x5e, 0x46, 0x70, 0xfd, 0xa1, 0x2d, 0xd7, 0x61, 0x33, 0x08, 0x5d, 0x0b, 0xf3, 0x48, 0x2a,
	0x66, 0xf2, 0x41, 0x3e, 0x84, 0x9d, 0xa4, 0x71, 0x82, 0x5d, 0x67, 0xc2, 0x78, 0x26, 0x15, 0xb3,
	0xca, 0xb1, 0x2f, 0x39, 0xd4, 0xef, 0x94, 0x1c, 0xab, 0x0b, 0x8e, 0x73, 0x0b, 0x6d, 0x15, 0x94,
	0x32, 0x96, 0x79, 0xee, 0xbd, 0xaa, 0xc0, 0x86, 0x41, 0x1d, 0xf9, 0x14, 0x76, 0x84, 0x2f, 0x85,
	0xfd, 0xd2, 0xcb, 0x24, 0xae, 0x61, 0xf5, 0xc3, 0x95, 0x74, 0xa6, 0x2e, 0xbf, 0x80, 0xbb, 0xa5,
	0x0d, 0xfd, 0x60, 0xa1, 0x51, 0x2c, 0x50, 0x1f, 0xde, 0x50, 0x90, 0x6b, 0x7f, 0x0d, 0x30, 0xb7,
	0x9d, 0xf6, 0x16, 0xda, 0x0a, 0x52, 0x7d, 0x7f, 0x05, 0x99, 0xeb, 0x7d, 0x03, 0xd5, 0xf9, 0x17,
	0xf5, 0xfe, 0x42, 0xcf, 0x1c, 0xab, 0x7e, 0xb0, 0x8a, 0xcd, 0x25, 0x4f, 0x61, 0x47, 0x78, 0x91,
	0xf6, 0x97, 0x76, 0x65, 0xf4, 0x92, 0x50, 0x97, 0x5d, 0x53, 0xf9, 0x7b, 0xb8, 0x23, 0x5e, 0x51,
	0x6d, 0x69, 0x5f, 0xce, 0xab, 0x1f, 0xad, 0xe6, 0x33, 0x61, 0x75, 0xf3, 0xc7, 0xeb, 0x8b, 0x8e,
	0x34, 0x38, 0x79, 0x7d, 0xa9, 0x49, 0x6f, 0x2e, 0x35, 0xe9, 0x9f, 0x4b, 0x4d, 0x7a, 0x75, 0xa5,
	0xad, 0xbd, 0xb9, 0xd2, 0xd6, 0xfe, 0xbe, 0xd2, 0xd6, 0x5e, 0x3c, 0x75, 0x5c, 0x36, 0x89, 0xc6,
	0x5d, 0x8b, 0x78, 0x7a, 0x10, 0xd1, 0x09, 0xbf, 0x90, 0xfc, 0x74, 0xc4, 0x8f, 0x47, 0x3e, 0xb1,
	0xb1, 0x3e, 0xd3, 0x8b, 0xbb, 0xc8, 0x7f, 0xcb, 0x8c, 0xb7, 0xf8, 0x8f, 0x8f, 0xcf, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x51, 0xf4, 0xad, 0x67, 0x39, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the parameters.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// ExecutePayload defines a message for executing a universal payload
	ExecutePayload(ctx context.Context, in *MsgExecutePayload, opts ...grpc.CallOption) (*MsgExecutePayloadResponse, error)
	// MigrateUEA defines a message for migrating UEA
	MigrateUEA(ctx context.Context, in *MsgMigrateUEA, opts ...grpc.CallOption) (*MsgMigrateUEAResponse, error)
	// VoteInbound defines a message for voting on synthetic assets bridging from external chain to PC
	VoteInbound(ctx context.Context, in *MsgVoteInbound, opts ...grpc.CallOption) (*MsgVoteInboundResponse, error)
	// VoteOutbound defines a message for voting on a observed outbound tx on external chain
	VoteOutbound(ctx context.Context, in *MsgVoteOutbound, opts ...grpc.CallOption) (*MsgVoteOutboundResponse, error)
	// VoteChainMeta defines a message for universal validators to vote on chain metadata (gas price + block height)
	VoteChainMeta(ctx context.Context, in *MsgVoteChainMeta, opts ...grpc.CallOption) (*MsgVoteChainMetaResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/uexecutor.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecutePayload(ctx context.Context, in *MsgExecutePayload, opts ...grpc.CallOption) (*MsgExecutePayloadResponse, error) {
	out := new(MsgExecutePayloadResponse)
	err := c.cc.Invoke(ctx, "/uexecutor.v1.Msg/ExecutePayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MigrateUEA(ctx context.Context, in *MsgMigrateUEA, opts ...grpc.CallOption) (*MsgMigrateUEAResponse, error) {
	out := new(MsgMigrateUEAResponse)
	err := c.cc.Invoke(ctx, "/uexecutor.v1.Msg/MigrateUEA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VoteInbound(ctx context.Context, in *MsgVoteInbound, opts ...grpc.CallOption) (*MsgVoteInboundResponse, error) {
	out := new(MsgVoteInboundResponse)
	err := c.cc.Invoke(ctx, "/uexecutor.v1.Msg/VoteInbound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VoteOutbound(ctx context.Context, in *MsgVoteOutbound, opts ...grpc.CallOption) (*MsgVoteOutboundResponse, error) {
	out := new(MsgVoteOutboundResponse)
	err := c.cc.Invoke(ctx, "/uexecutor.v1.Msg/VoteOutbound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VoteChainMeta(ctx context.Context, in *MsgVoteChainMeta, opts ...grpc.CallOption) (*MsgVoteChainMetaResponse, error) {
	out := new(MsgVoteChainMetaResponse)
	err := c.cc.Invoke(ctx, "/uexecutor.v1.Msg/VoteChainMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the parameters.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// ExecutePayload defines a message for executing a universal payload
	ExecutePayload(context.Context, *MsgExecutePayload) (*MsgExecutePayloadResponse, error)
	// MigrateUEA defines a message for migrating UEA
	MigrateUEA(context.Context, *MsgMigrateUEA) (*MsgMigrateUEAResponse, error)
	// VoteInbound defines a message for voting on synthetic assets bridging from external chain to PC
	VoteInbound(context.Context, *MsgVoteInbound) (*MsgVoteInboundResponse, error)
	// VoteOutbound defines a message for voting on a observed outbound tx on external chain
	VoteOutbound(context.Context, *MsgVoteOutbound) (*MsgVoteOutboundResponse, error)
	// VoteChainMeta defines a message for universal validators to vote on chain metadata (gas price + block height)
	VoteChainMeta(context.Context, *MsgVoteChainMeta) (*MsgVoteChainMetaResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) ExecutePayload(ctx context.Context, req *MsgExecutePayload) (*MsgExecutePayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePayload not implemented")
}
func (*UnimplementedMsgServer) MigrateUEA(ctx context.Context, req *MsgMigrateUEA) (*MsgMigrateUEAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateUEA not implemented")
}
func (*UnimplementedMsgServer) VoteInbound(ctx context.Context, req *MsgVoteInbound) (*MsgVoteInboundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteInbound not implemented")
}
func (*UnimplementedMsgServer) VoteOutbound(ctx context.Context, req *MsgVoteOutbound) (*MsgVoteOutboundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteOutbound not implemented")
}
func (*UnimplementedMsgServer) VoteChainMeta(ctx context.Context, req *MsgVoteChainMeta) (*MsgVoteChainMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteChainMeta not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uexecutor.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecutePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecutePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecutePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uexecutor.v1.Msg/ExecutePayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecutePayload(ctx, req.(*MsgExecutePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MigrateUEA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMigrateUEA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MigrateUEA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uexecutor.v1.Msg/MigrateUEA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MigrateUEA(ctx, req.(*MsgMigrateUEA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VoteInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVoteInbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VoteInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uexecutor.v1.Msg/VoteInbound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VoteInbound(ctx, req.(*MsgVoteInbound))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VoteOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVoteOutbound)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VoteOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uexecutor.v1.Msg/VoteOutbound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VoteOutbound(ctx, req.(*MsgVoteOutbound))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VoteChainMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVoteChainMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VoteChainMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uexecutor.v1.Msg/VoteChainMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VoteChainMeta(ctx, req.(*MsgVoteChainMeta))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uexecutor.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "ExecutePayload",
			Handler:    _Msg_ExecutePayload_Handler,
		},
		{
			MethodName: "MigrateUEA",
			Handler:    _Msg_MigrateUEA_Handler,
		},
		{
			MethodName: "VoteInbound",
			Handler:    _Msg_VoteInbound_Handler,
		},
		{
			MethodName: "VoteOutbound",
			Handler:    _Msg_VoteOutbound_Handler,
		},
		{
			MethodName: "VoteChainMeta",
			Handler:    _Msg_VoteChainMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uexecutor/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgExecutePayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecutePayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecutePayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationData) > 0 {
		i -= len(m.VerificationData)
		copy(dAtA[i:], m.VerificationData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerificationData)))
		i--
		dAtA[i] = 0x22
	}
	if m.UniversalPayload != nil {
		{
			size, err := m.UniversalPayload.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UniversalAccountId != nil {
		{
			size, err := m.UniversalAccountId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecutePayloadResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecutePayloadResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecutePayloadResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMigrateUEA) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrateUEA) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrateUEA) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x22
	}
	if m.MigrationPayload != nil {
		{
			size, err := m.MigrationPayload.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UniversalAccountId != nil {
		{
			size, err := m.UniversalAccountId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMigrateUEAResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMigrateUEAResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMigrateUEAResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgVoteInbound) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteInbound) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteInbound) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Inbound != nil {
		{
			size, err := m.Inbound.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteInboundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteInboundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteInboundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgVoteOutbound) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteOutbound) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteOutbound) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ObservedTx != nil {
		{
			size, err := m.ObservedTx.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.UtxId) > 0 {
		i -= len(m.UtxId)
		copy(dAtA[i:], m.UtxId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UtxId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteOutboundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteOutboundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteOutboundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgVoteChainMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteChainMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteChainMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ChainHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ObservedChainId) > 0 {
		i -= len(m.ObservedChainId)
		copy(dAtA[i:], m.ObservedChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ObservedChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteChainMetaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteChainMetaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteChainMetaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgExecutePayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.UniversalAccountId != nil {
		l = m.UniversalAccountId.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.UniversalPayload != nil {
		l = m.UniversalPayload.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VerificationData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgExecutePayloadResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMigrateUEA) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.UniversalAccountId != nil {
		l = m.UniversalAccountId.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MigrationPayload != nil {
		l = m.MigrationPayload.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgMigrateUEAResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgVoteInbound) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Inbound != nil {
		l = m.Inbound.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgVoteInboundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgVoteOutbound) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UtxId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ObservedTx != nil {
		l = m.ObservedTx.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgVoteOutboundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgVoteChainMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ObservedChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	if m.ChainHeight != 0 {
		n += 1 + sovTx(uint64(m.ChainHeight))
	}
	return n
}

func (m *MsgVoteChainMetaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecutePayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecutePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecutePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversalAccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UniversalAccountId == nil {
				m.UniversalAccountId = &UniversalAccountId{}
			}
			if err := m.UniversalAccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversalPayload", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UniversalPayload == nil {
				m.UniversalPayload = &UniversalPayload{}
			}
			if err := m.UniversalPayload.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecutePayloadResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecutePayloadResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecutePayloadResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMigrateUEA) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrateUEA: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrateUEA: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversalAccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UniversalAccountId == nil {
				m.UniversalAccountId = &UniversalAccountId{}
			}
			if err := m.UniversalAccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationPayload", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MigrationPayload == nil {
				m.MigrationPayload = &MigrationPayload{}
			}
			if err := m.MigrationPayload.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMigrateUEAResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMigrateUEAResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMigrateUEAResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteInbound) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteInbound: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteInbound: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inbound", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Inbound == nil {
				m.Inbound = &Inbound{}
			}
			if err := m.Inbound.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteInboundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteInboundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteInboundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteOutbound) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteOutbound: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteOutbound: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UtxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UtxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedTx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ObservedTx == nil {
				m.ObservedTx = &OutboundObservation{}
			}
			if err := m.ObservedTx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteOutboundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteOutboundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteOutboundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteChainMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteChainMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteChainMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservedChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainHeight", wireType)
			}
			m.ChainHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteChainMetaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteChainMetaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteChainMetaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
