// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ucallback/v1/types.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/pushchain/push-chain-node/x/uexecutor/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ReadStatus is the outcome a universal validator observed for a read.
type ReadStatus int32

const (
	ReadStatus_READ_STATUS_UNSPECIFIED ReadStatus = 0
	ReadStatus_READ_STATUS_SUCCESS     ReadStatus = 1
	ReadStatus_READ_STATUS_ERROR       ReadStatus = 2
)

var ReadStatus_name = map[int32]string{
	0: "READ_STATUS_UNSPECIFIED",
	1: "READ_STATUS_SUCCESS",
	2: "READ_STATUS_ERROR",
}

var ReadStatus_value = map[string]int32{
	"READ_STATUS_UNSPECIFIED": 0,
	"READ_STATUS_SUCCESS":     1,
	"READ_STATUS_ERROR":       2,
}

func (x ReadStatus) String() string {
	return proto.EnumName(ReadStatus_name, int32(x))
}

func (ReadStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bdb5182bd84a8426, []int{0}
}

// UniversalReadStatus is the lifecycle state of a read request on Push Chain.
type UniversalReadStatus int32

const (
	UniversalReadStatus_UNIVERSAL_READ_STATUS_UNSPECIFIED UniversalReadStatus = 0
	UniversalReadStatus_UNIVERSAL_READ_STATUS_PENDING     UniversalReadStatus = 1
	UniversalReadStatus_UNIVERSAL_READ_STATUS_VOTING      UniversalReadStatus = 2
	UniversalReadStatus_UNIVERSAL_READ_STATUS_FULFILLED   UniversalReadStatus = 3
	UniversalReadStatus_UNIVERSAL_READ_STATUS_EXPIRED     UniversalReadStatus = 4
	UniversalReadStatus_UNIVERSAL_READ_STATUS_FAILED      UniversalReadStatus = 5
)

var UniversalReadStatus_name = map[int32]string{
	0: "UNIVERSAL_READ_STATUS_UNSPECIFIED",
	1: "UNIVERSAL_READ_STATUS_PENDING",
	2: "UNIVERSAL_READ_STATUS_VOTING",
	3: "UNIVERSAL_READ_STATUS_FULFILLED",
	4: "UNIVERSAL_READ_STATUS_EXPIRED",
	5: "UNIVERSAL_READ_STATUS_FAILED",
}

var UniversalReadStatus_value = map[string]int32{
	"UNIVERSAL_READ_STATUS_UNSPECIFIED": 0,
	"UNIVERSAL_READ_STATUS_PENDING":     1,
	"UNIVERSAL_READ_STATUS_VOTING":      2,
	"UNIVERSAL_READ_STATUS_FULFILLED":   3,
	"UNIVERSAL_READ_STATUS_EXPIRED":     4,
	"UNIVERSAL_READ_STATUS_FAILED":      5,
}

func (x UniversalReadStatus) String() string {
	return proto.EnumName(UniversalReadStatus_name, int32(x))
}

func (UniversalReadStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bdb5182bd84a8426, []int{1}
}

// ReadRequest is one external read requested by an app on Push Chain.
//
// Every field is derived from the UniversalCallback.ReadRequested event, except
// created_at_height / requested_tx_hash / requested_log_index which come from the
// block the log was emitted in.
//
// NOTE: callbackGasLimit is deliberately absent. It is an argument to
// requestExternalReadSelf and is stored in the contract's _pending entry, but it is
// NOT emitted in ReadRequested. It has to be read back via getPendingRead(requestId)
// at fulfilment time, when the gas budget is actually needed.
type ReadRequest struct {
	RequestId              string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DestinationChain       string `protobuf:"bytes,2,opt,name=destination_chain,json=destinationChain,proto3" json:"destination_chain,omitempty"`
	Owner                  []byte `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Query                  []byte `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	MinConfirmations       uint32 `protobuf:"varint,5,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
	DestinationBlockHeight uint64 `protobuf:"varint,6,opt,name=destination_block_height,json=destinationBlockHeight,proto3" json:"destination_block_height,omitempty"`
	ExpiryBlockHeight      uint64 `protobuf:"varint,7,opt,name=expiry_block_height,json=expiryBlockHeight,proto3" json:"expiry_block_height,omitempty"`
	CreatedAtHeight        uint64 `protobuf:"varint,8,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
	// Bookkeeping — recorded for operators, not consumed by universal validators.
	CallbackTarget    string `protobuf:"bytes,9,opt,name=callback_target,json=callbackTarget,proto3" json:"callback_target,omitempty"`
	OriginalFunder    string `protobuf:"bytes,10,opt,name=original_funder,json=originalFunder,proto3" json:"original_funder,omitempty"`
	FeesDeposited     string `protobuf:"bytes,11,opt,name=fees_deposited,json=feesDeposited,proto3" json:"fees_deposited,omitempty"`
	MaxFee            string `protobuf:"bytes,12,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	RequestedTxHash   string `protobuf:"bytes,13,opt,name=requested_tx_hash,json=requestedTxHash,proto3" json:"requested_tx_hash,omitempty"`
	RequestedLogIndex uint64 `protobuf:"varint,14,opt,name=requested_log_index,json=requestedLogIndex,proto3" json:"requested_log_index,omitempty"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb5182bd84a8426, []int{0}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return m.Size()
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ReadRequest) GetDestinationChain() string {
	if m != nil {
		return m.DestinationChain
	}
	return ""
}

func (m *ReadRequest) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ReadRequest) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ReadRequest) GetMinConfirmations() uint32 {
	if m != nil {
		return m.MinConfirmations
	}
	return 0
}

func (m *ReadRequest) GetDestinationBlockHeight() uint64 {
	if m != nil {
		return m.DestinationBlockHeight
	}
	return 0
}

func (m *ReadRequest) GetExpiryBlockHeight() uint64 {
	if m != nil {
		return m.ExpiryBlockHeight
	}
	return 0
}

func (m *ReadRequest) GetCreatedAtHeight() uint64 {
	if m != nil {
		return m.CreatedAtHeight
	}
	return 0
}

func (m *ReadRequest) GetCallbackTarget() string {
	if m != nil {
		return m.CallbackTarget
	}
	return ""
}

func (m *ReadRequest) GetOriginalFunder() string {
	if m != nil {
		return m.OriginalFunder
	}
	return ""
}

func (m *ReadRequest) GetFeesDeposited() string {
	if m != nil {
		return m.FeesDeposited
	}
	return ""
}

func (m *ReadRequest) GetMaxFee() string {
	if m != nil {
		return m.MaxFee
	}
	return ""
}

func (m *ReadRequest) GetRequestedTxHash() string {
	if m != nil {
		return m.RequestedTxHash
	}
	return ""
}

func (m *ReadRequest) GetRequestedLogIndex() uint64 {
	if m != nil {
		return m.RequestedLogIndex
	}
	return 0
}

// ReadResult is the observation a universal validator votes on.
//
// Fields 1-4 are covered by the ballot key, so they must be byte-identical across
// validators for a ballot to converge. There is deliberately no error message field:
// local error text differs per node and would prevent agreement.
type ReadResult struct {
	Status              ReadStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ucallback.v1.ReadStatus" json:"status,omitempty"`
	ResultData          []byte     `protobuf:"bytes,2,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ObservedBlockHeight uint64     `protobuf:"varint,3,opt,name=observed_block_height,json=observedBlockHeight,proto3" json:"observed_block_height,omitempty"`
	ObservedBlockHash   []byte     `protobuf:"bytes,4,opt,name=observed_block_hash,json=observedBlockHash,proto3" json:"observed_block_hash,omitempty"`
	// v2 ONLY — always empty in v1. See AggregateValue.
	Aggregates []*AggregateValue `protobuf:"bytes,5,rep,name=aggregates,proto3" json:"aggregates,omitempty"`
}

func (m *ReadResult) Reset()         { *m = ReadResult{} }
func (m *ReadResult) String() string { return proto.CompactTextString(m) }
func (*ReadResult) ProtoMessage()    {}
func (*ReadResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb5182bd84a8426, []int{1}
}
func (m *ReadResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResult.Merge(m, src)
}
func (m *ReadResult) XXX_Size() int {
	return m.Size()
}
func (m *ReadResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResult proto.InternalMessageInfo

func (m *ReadResult) GetStatus() ReadStatus {
	if m != nil {
		return m.Status
	}
	return ReadStatus_READ_STATUS_UNSPECIFIED
}

func (m *ReadResult) GetResultData() []byte {
	if m != nil {
		return m.ResultData
	}
	return nil
}

func (m *ReadResult) GetObservedBlockHeight() uint64 {
	if m != nil {
		return m.ObservedBlockHeight
	}
	return 0
}

func (m *ReadResult) GetObservedBlockHash() []byte {
	if m != nil {
		return m.ObservedBlockHash
	}
	return nil
}

func (m *ReadResult) GetAggregates() []*AggregateValue {
	if m != nil {
		return m.Aggregates
	}
	return nil
}

// AggregateValue is one field the module combines across validators instead of
// requiring byte-equality on — a price, say, where honest nodes legitimately differ.
//
// NOT USED IN v1. The universal client rejects any extract mode other than IDENTICAL
// (externalchains/web2/read_envelope.go), so this list is always empty today. The field
// is reserved now because adding it later would change how ballots are keyed on a live
// chain, which is consensus-breaking. In v1 the ballot key covers all of fields 1-4; in
// v2 it must cover only fields 1-4 with `aggregates` EXCLUDED, so computing the key over
// "the identical subset" from the start keeps v2 purely additive.
//
// v2 ALSO REQUIRES REPLACING THE BALLOT MECHANISM, not just populating this field.
// Ballots today store a binary VoteResult{SUCCESS|FAILURE} against an ID that encodes the
// observation, so distinct observations produce distinct ballots and none reaches quorum
// when validators report different numbers. Ballots therefore cannot retain per-validator
// values, which is exactly what a median needs. v2 has to keep each validator's
// AggregateValue set in module state and reduce at quorum — the pattern x/uexecutor
// already uses for gas-price medians in keeper/chain_meta.go, which bypasses ballots for
// the same reason.
type AggregateValue struct {
	ExtractIndex uint32 `protobuf:"varint,1,opt,name=extract_index,json=extractIndex,proto3" json:"extract_index,omitempty"`
	Mode         uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Value        []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *AggregateValue) Reset()         { *m = AggregateValue{} }
func (m *AggregateValue) String() string { return proto.CompactTextString(m) }
func (*AggregateValue) ProtoMessage()    {}
func (*AggregateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb5182bd84a8426, []int{2}
}
func (m *AggregateValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AggregateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AggregateValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AggregateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateValue.Merge(m, src)
}
func (m *AggregateValue) XXX_Size() int {
	return m.Size()
}
func (m *AggregateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateValue.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateValue proto.InternalMessageInfo

func (m *AggregateValue) GetExtractIndex() uint32 {
	if m != nil {
		return m.ExtractIndex
	}
	return 0
}

func (m *AggregateValue) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *AggregateValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// UniversalRead is the full lifecycle record of one read request.
//
// The read-side sibling of uexecutor's UniversalTx, but deliberately not the same
// shape: a read is triggered by a Push Chain event rather than an external inbound,
// performs no external write, and settles in exactly one Push Chain transaction.
type UniversalRead struct {
	Id        string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Request   *ReadRequest        `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Result    *ReadResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Status    UniversalReadStatus `protobuf:"varint,4,opt,name=status,proto3,enum=ucallback.v1.UniversalReadStatus" json:"status,omitempty"`
	BallotKey string              `protobuf:"bytes,5,opt,name=ballot_key,json=ballotKey,proto3" json:"ballot_key,omitempty"`
	// Push Chain execution attempts — fulfilExternalCallback and expireExternalRead.
	// Repeated because fulfilment can be retried and may be followed by an expiry.
	PcTx []*types.PCTx `protobuf:"bytes,6,rep,name=pc_tx,json=pcTx,proto3" json:"pc_tx,omitempty"`
}

func (m *UniversalRead) Reset()         { *m = UniversalRead{} }
func (m *UniversalRead) String() string { return proto.CompactTextString(m) }
func (*UniversalRead) ProtoMessage()    {}
func (*UniversalRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb5182bd84a8426, []int{3}
}
func (m *UniversalRead) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UniversalRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UniversalRead.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UniversalRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniversalRead.Merge(m, src)
}
func (m *UniversalRead) XXX_Size() int {
	return m.Size()
}
func (m *UniversalRead) XXX_DiscardUnknown() {
	xxx_messageInfo_UniversalRead.DiscardUnknown(m)
}

var xxx_messageInfo_UniversalRead proto.InternalMessageInfo

func (m *UniversalRead) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UniversalRead) GetRequest() *ReadRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *UniversalRead) GetResult() *ReadResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UniversalRead) GetStatus() UniversalReadStatus {
	if m != nil {
		return m.Status
	}
	return UniversalReadStatus_UNIVERSAL_READ_STATUS_UNSPECIFIED
}

func (m *UniversalRead) GetBallotKey() string {
	if m != nil {
		return m.BallotKey
	}
	return ""
}

func (m *UniversalRead) GetPcTx() []*types.PCTx {
	if m != nil {
		return m.PcTx
	}
	return nil
}

func init() {
	proto.RegisterEnum("ucallback.v1.ReadStatus", ReadStatus_name, ReadStatus_value)
	proto.RegisterEnum("ucallback.v1.UniversalReadStatus", UniversalReadStatus_name, UniversalReadStatus_value)
	proto.RegisterType((*ReadRequest)(nil), "ucallback.v1.ReadRequest")
	proto.RegisterType((*ReadResult)(nil), "ucallback.v1.ReadResult")
	proto.RegisterType((*AggregateValue)(nil), "ucallback.v1.AggregateValue")
	proto.RegisterType((*UniversalRead)(nil), "ucallback.v1.UniversalRead")
}

func init() { proto.RegisterFile("ucallback/v1/types.proto", fileDescriptor_bdb5182bd84a8426) }

var fileDescriptor_bdb5182bd84a8426 = []byte{
	// 939 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x65, 0xd9, 0xa9, 0x56, 0x3f, 0x96, 0xd6, 0x49, 0xcd, 0xba, 0xb1, 0x2c, 0x27, 0x08,
	0x22, 0xb8, 0x88, 0xd4, 0x38, 0x40, 0xd1, 0x06, 0xbd, 0x28, 0x12, 0xd5, 0x08, 0x15, 0x1c, 0x61,
	0x25, 0x19, 0x45, 0x2f, 0x8b, 0x15, 0x39, 0xa6, 0x08, 0x53, 0xa4, 0x42, 0x2e, 0x55, 0xea, 0x09,
	0x0a, 0xf4, 0xd4, 0x47, 0xe8, 0xa1, 0x87, 0x1e, 0x7a, 0xe8, 0x03, 0xf4, 0x01, 0x7a, 0xcc, 0xb1,
	0xc7, 0xc2, 0x3e, 0xb4, 0xd7, 0xbe, 0x41, 0xb1, 0x4b, 0x52, 0xa1, 0x5c, 0xf9, 0x22, 0x2c, 0xbf,
	0xef, 0xdb, 0x99, 0xd9, 0xf9, 0x66, 0xb5, 0x48, 0x0d, 0x74, 0x66, 0xdb, 0x13, 0xa6, 0x5f, 0x35,
	0x17, 0xcf, 0x9b, 0x7c, 0x39, 0x07, 0xbf, 0x31, 0xf7, 0x5c, 0xee, 0xe2, 0xc2, 0x8a, 0x69, 0x2c,
	0x9e, 0x1f, 0xde, 0x37, 0x5d, 0xd3, 0x95, 0x44, 0x53, 0xac, 0x22, 0xcd, 0x61, 0x85, 0xcd, 0x2c,
	0xc7, 0x6d, 0xca, 0xdf, 0x18, 0x52, 0x03, 0x08, 0x41, 0x0f, 0xb8, 0xeb, 0xdd, 0x0a, 0xf8, 0xe8,
	0xf7, 0x2c, 0xca, 0x13, 0x60, 0x06, 0x81, 0xb7, 0x01, 0xf8, 0x1c, 0x1f, 0x21, 0xe4, 0x45, 0x4b,
	0x6a, 0x19, 0xaa, 0x52, 0x53, 0xea, 0x39, 0x92, 0x8b, 0x91, 0x9e, 0x81, 0x3f, 0x41, 0x15, 0x03,
	0x7c, 0x6e, 0x39, 0x8c, 0x5b, 0xae, 0x43, 0xf5, 0x29, 0xb3, 0x1c, 0x35, 0x23, 0x55, 0xe5, 0x14,
	0xd1, 0x16, 0x38, 0xbe, 0x8f, 0x76, 0xdc, 0xef, 0x1c, 0xf0, 0xd4, 0xed, 0x9a, 0x52, 0x2f, 0x90,
	0xe8, 0x43, 0xa0, 0x6f, 0x03, 0xf0, 0x96, 0x6a, 0x36, 0x42, 0xe5, 0x87, 0x08, 0x3c, 0xb3, 0x1c,
	0xaa, 0xbb, 0xce, 0xa5, 0xe5, 0xcd, 0x64, 0x10, 0x5f, 0xdd, 0xa9, 0x29, 0xf5, 0x22, 0x29, 0xcf,
	0x2c, 0xa7, 0x9d, 0xc6, 0xf1, 0xe7, 0x48, 0x4d, 0x57, 0x31, 0xb1, 0x5d, 0xfd, 0x8a, 0x4e, 0xc1,
	0x32, 0xa7, 0x5c, 0xdd, 0xad, 0x29, 0xf5, 0x2c, 0xf9, 0x30, 0xc5, 0xbf, 0x12, 0xf4, 0x6b, 0xc9,
	0xe2, 0x06, 0xda, 0x87, 0x70, 0x6e, 0x79, 0xcb, 0xf5, 0x4d, 0xf7, 0xe4, 0xa6, 0x4a, 0x44, 0xa5,
	0xf5, 0xa7, 0xa8, 0xa2, 0x7b, 0xc0, 0x38, 0x18, 0x94, 0xf1, 0x44, 0xfd, 0x81, 0x54, 0xef, 0xc5,
	0x44, 0x8b, 0xc7, 0xda, 0xa7, 0x68, 0x2f, 0x31, 0x87, 0x72, 0xe6, 0x99, 0xc0, 0xd5, 0x9c, 0xec,
	0x4c, 0x29, 0x81, 0x47, 0x12, 0x15, 0x42, 0xd7, 0xb3, 0x4c, 0xcb, 0x61, 0x36, 0xbd, 0x0c, 0x1c,
	0x03, 0x3c, 0x15, 0x45, 0xc2, 0x04, 0xee, 0x4a, 0x14, 0x3f, 0x41, 0xa5, 0x4b, 0x00, 0x9f, 0x1a,
	0x30, 0x77, 0x7d, 0x8b, 0x83, 0xa1, 0xe6, 0xa5, 0xae, 0x28, 0xd0, 0x4e, 0x02, 0xe2, 0x03, 0x74,
	0x6f, 0xc6, 0x42, 0x7a, 0x09, 0xa0, 0x16, 0x24, 0xbf, 0x3b, 0x63, 0x61, 0x17, 0x40, 0x54, 0x1f,
	0x5b, 0x07, 0x06, 0xe5, 0x21, 0x9d, 0x32, 0x7f, 0xaa, 0x16, 0xa5, 0x64, 0x6f, 0x45, 0x8c, 0xc2,
	0xd7, 0xcc, 0x9f, 0x8a, 0xce, 0xbc, 0xd7, 0xda, 0xae, 0x49, 0x2d, 0xc7, 0x80, 0x50, 0x2d, 0x45,
	0x9d, 0x59, 0x51, 0x7d, 0xd7, 0xec, 0x09, 0xe2, 0x65, 0xf6, 0x9f, 0x9f, 0x8e, 0x95, 0x47, 0xdf,
	0x67, 0x10, 0x8a, 0xc6, 0xc7, 0x0f, 0x6c, 0x8e, 0x3f, 0x45, 0xbb, 0x3e, 0x67, 0x3c, 0xf0, 0xe5,
	0xe4, 0x94, 0xce, 0xd4, 0x46, 0x7a, 0x5e, 0x1b, 0x42, 0x39, 0x94, 0x3c, 0x89, 0x75, 0xf8, 0x18,
	0xe5, 0x3d, 0xb9, 0x97, 0x1a, 0x8c, 0x33, 0x39, 0x4a, 0x05, 0x82, 0x22, 0xa8, 0xc3, 0x38, 0xc3,
	0x67, 0xe8, 0x81, 0x3b, 0xf1, 0xc1, 0x5b, 0x80, 0xb1, 0xee, 0xd9, 0xb6, 0xac, 0x6c, 0x3f, 0x21,
	0x6f, 0xb9, 0x7c, 0x7b, 0x8f, 0x38, 0x79, 0x34, 0x70, 0x95, 0xf5, 0x1d, 0xe2, 0xec, 0x5f, 0x22,
	0xc4, 0x4c, 0xd3, 0x03, 0x93, 0x71, 0x10, 0x53, 0xb7, 0x5d, 0xcf, 0x9f, 0x3d, 0x5c, 0x2f, 0xbd,
	0x95, 0xf0, 0x17, 0xcc, 0x0e, 0x80, 0xa4, 0xf4, 0x71, 0x27, 0x00, 0x95, 0xd6, 0x35, 0xf8, 0x31,
	0x2a, 0x42, 0xc8, 0x3d, 0xa6, 0xf3, 0xb8, 0x97, 0x8a, 0x1c, 0xe7, 0x42, 0x0c, 0xca, 0x36, 0x62,
	0x8c, 0xb2, 0x33, 0xd7, 0x00, 0x79, 0xf0, 0x22, 0x91, 0x6b, 0x71, 0x43, 0x16, 0x22, 0x42, 0x72,
	0x6f, 0xe4, 0x47, 0x9c, 0xe6, 0xd7, 0x0c, 0x2a, 0x8e, 0x1d, 0x6b, 0x01, 0x9e, 0xcf, 0x6c, 0xd1,
	0x4f, 0x5c, 0x42, 0x99, 0xd5, 0x4d, 0xcd, 0x58, 0x06, 0x7e, 0x81, 0xee, 0xc5, 0x6e, 0xc9, 0xa0,
	0xf9, 0xb3, 0x8f, 0xfe, 0x6f, 0x42, 0x7c, 0xdb, 0x49, 0xa2, 0x14, 0xc6, 0x45, 0x3d, 0x97, 0x39,
	0xf3, 0x9b, 0x8c, 0x8b, 0x2c, 0x26, 0xb1, 0x0e, 0x7f, 0xb1, 0xb2, 0x3a, 0x2b, 0xad, 0x3e, 0x59,
	0xdf, 0xb1, 0x56, 0xe3, 0x2d, 0xcf, 0x8f, 0x10, 0x9a, 0x30, 0xdb, 0x76, 0x39, 0xbd, 0x82, 0xa5,
	0xbc, 0xe4, 0x39, 0x92, 0x8b, 0x90, 0xaf, 0x61, 0x89, 0x9f, 0xa2, 0x9d, 0xb9, 0x4e, 0x79, 0xa8,
	0xee, 0x4a, 0x23, 0x70, 0x63, 0xf5, 0xe7, 0x25, 0x02, 0x0f, 0xda, 0xa3, 0x90, 0x64, 0xe7, 0xfa,
	0x28, 0x7c, 0x79, 0x22, 0x3a, 0xf2, 0xc3, 0xdf, 0xbf, 0x9d, 0xa6, 0xfe, 0x2f, 0x83, 0x24, 0x2f,
	0xf5, 0x80, 0x19, 0xa7, 0x34, 0x1a, 0xcf, 0xa8, 0x00, 0xfc, 0x31, 0x3a, 0x20, 0x5a, 0xab, 0x43,
	0x87, 0xa3, 0xd6, 0x68, 0x3c, 0xa4, 0xe3, 0xf3, 0xe1, 0x40, 0x6b, 0xf7, 0xba, 0x3d, 0xad, 0x53,
	0xde, 0xc2, 0x07, 0x68, 0x3f, 0x4d, 0x0e, 0xc7, 0xed, 0xb6, 0x36, 0x1c, 0x96, 0x15, 0xfc, 0x00,
	0x55, 0xd2, 0x84, 0x46, 0xc8, 0x1b, 0x52, 0xce, 0x1c, 0x66, 0x7f, 0xf9, 0xb9, 0xaa, 0x9c, 0xfe,
	0xab, 0xa0, 0xfd, 0x0d, 0x67, 0xc5, 0x4f, 0xd0, 0xc9, 0xf8, 0xbc, 0x77, 0xa1, 0x91, 0x61, 0xab,
	0x4f, 0xef, 0x4e, 0x7a, 0x82, 0x8e, 0x36, 0xcb, 0x06, 0xda, 0x79, 0xa7, 0x77, 0xfe, 0x55, 0x59,
	0xc1, 0x35, 0xf4, 0x70, 0xb3, 0xe4, 0xe2, 0xcd, 0x48, 0x28, 0x32, 0xf8, 0x31, 0x3a, 0xde, 0xac,
	0xe8, 0x8e, 0xfb, 0xdd, 0x5e, 0xbf, 0xaf, 0x75, 0xca, 0xdb, 0x77, 0x67, 0xd2, 0xbe, 0x19, 0xf4,
	0x88, 0xd6, 0x29, 0x67, 0xef, 0xce, 0xd4, 0x6d, 0xf5, 0x44, 0x90, 0x9d, 0xe8, 0xcc, 0xaf, 0x06,
	0x7f, 0x5c, 0x57, 0x95, 0x77, 0xd7, 0x55, 0xe5, 0xaf, 0xeb, 0xaa, 0xf2, 0xe3, 0x4d, 0x75, 0xeb,
	0xdd, 0x4d, 0x75, 0xeb, 0xcf, 0x9b, 0xea, 0xd6, 0xb7, 0x9f, 0x99, 0x16, 0x9f, 0x06, 0x93, 0x86,
	0xee, 0xce, 0x9a, 0xf3, 0xc0, 0x9f, 0xca, 0xf7, 0x41, 0xae, 0x9e, 0xc9, 0xe5, 0x33, 0xc7, 0x35,
	0xa0, 0x19, 0x36, 0xdf, 0xfb, 0x25, 0xdf, 0xa2, 0xc9, 0xae, 0x7c, 0x8c, 0x5e, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x80, 0x05, 0x37, 0x8d, 0xf9, 0x06, 0x00, 0x00,
}

func (this *ReadRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReadRequest)
	if !ok {
		that2, ok := that.(ReadRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RequestId != that1.RequestId {
		return false
	}
	if this.DestinationChain != that1.DestinationChain {
		return false
	}
	if !bytes.Equal(this.Owner, that1.Owner) {
		return false
	}
	if !bytes.Equal(this.Query, that1.Query) {
		return false
	}
	if this.MinConfirmations != that1.MinConfirmations {
		return false
	}
	if this.DestinationBlockHeight != that1.DestinationBlockHeight {
		return false
	}
	if this.ExpiryBlockHeight != that1.ExpiryBlockHeight {
		return false
	}
	if this.CreatedAtHeight != that1.CreatedAtHeight {
		return false
	}
	if this.CallbackTarget != that1.CallbackTarget {
		return false
	}
	if this.OriginalFunder != that1.OriginalFunder {
		return false
	}
	if this.FeesDeposited != that1.FeesDeposited {
		return false
	}
	if this.MaxFee != that1.MaxFee {
		return false
	}
	if this.RequestedTxHash != that1.RequestedTxHash {
		return false
	}
	if this.RequestedLogIndex != that1.RequestedLogIndex {
		return false
	}
	return true
}
func (this *ReadResult) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReadResult)
	if !ok {
		that2, ok := that.(ReadResult)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !bytes.Equal(this.ResultData, that1.ResultData) {
		return false
	}
	if this.ObservedBlockHeight != that1.ObservedBlockHeight {
		return false
	}
	if !bytes.Equal(this.ObservedBlockHash, that1.ObservedBlockHash) {
		return false
	}
	if len(this.Aggregates) != len(that1.Aggregates) {
		return false
	}
	for i := range this.Aggregates {
		if !this.Aggregates[i].Equal(that1.Aggregates[i]) {
			return false
		}
	}
	return true
}
func (this *AggregateValue) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AggregateValue)
	if !ok {
		that2, ok := that.(AggregateValue)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ExtractIndex != that1.ExtractIndex {
		return false
	}
	if this.Mode != that1.Mode {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	return true
}
func (this *UniversalRead) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UniversalRead)
	if !ok {
		that2, ok := that.(UniversalRead)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if !this.Request.Equal(that1.Request) {
		return false
	}
	if !this.Result.Equal(that1.Result) {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.BallotKey != that1.BallotKey {
		return false
	}
	if len(this.PcTx) != len(that1.PcTx) {
		return false
	}
	for i := range this.PcTx {
		if !this.PcTx[i].Equal(that1.PcTx[i]) {
			return false
		}
	}
	return true
}
func (m *ReadRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestedLogIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RequestedLogIndex))
		i--
		dAtA[i] = 0x70
	}
	if len(m.RequestedTxHash) > 0 {
		i -= len(m.RequestedTxHash)
		copy(dAtA[i:], m.RequestedTxHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RequestedTxHash)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.MaxFee) > 0 {
		i -= len(m.MaxFee)
		copy(dAtA[i:], m.MaxFee)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MaxFee)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.FeesDeposited) > 0 {
		i -= len(m.FeesDeposited)
		copy(dAtA[i:], m.FeesDeposited)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.FeesDeposited)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.OriginalFunder) > 0 {
		i -= len(m.OriginalFunder)
		copy(dAtA[i:], m.OriginalFunder)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OriginalFunder)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.CallbackTarget) > 0 {
		i -= len(m.CallbackTarget)
		copy(dAtA[i:], m.CallbackTarget)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CallbackTarget)))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedAtHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAtHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.ExpiryBlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiryBlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.DestinationBlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DestinationBlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.MinConfirmations != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MinConfirmations))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Query) > 0 {
		i -= len(m.Query)
		copy(dAtA[i:], m.Query)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Query)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DestinationChain) > 0 {
		i -= len(m.DestinationChain)
		copy(dAtA[i:], m.DestinationChain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DestinationChain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReadResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Aggregates) > 0 {
		for iNdEx := len(m.Aggregates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Aggregates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ObservedBlockHash) > 0 {
		i -= len(m.ObservedBlockHash)
		copy(dAtA[i:], m.ObservedBlockHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ObservedBlockHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.ObservedBlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ObservedBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ResultData) > 0 {
		i -= len(m.ResultData)
		copy(dAtA[i:], m.ResultData)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ResultData)))
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AggregateValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AggregateValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregateValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Mode != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x10
	}
	if m.ExtractIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExtractIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UniversalRead) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UniversalRead) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversalRead) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PcTx) > 0 {
		for iNdEx := len(m.PcTx) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PcTx[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.BallotKey) > 0 {
		i -= len(m.BallotKey)
		copy(dAtA[i:], m.BallotKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BallotKey)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Request != nil {
		{
			size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReadRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DestinationChain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.MinConfirmations != 0 {
		n += 1 + sovTypes(uint64(m.MinConfirmations))
	}
	if m.DestinationBlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.DestinationBlockHeight))
	}
	if m.ExpiryBlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.ExpiryBlockHeight))
	}
	if m.CreatedAtHeight != 0 {
		n += 1 + sovTypes(uint64(m.CreatedAtHeight))
	}
	l = len(m.CallbackTarget)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OriginalFunder)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.FeesDeposited)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.MaxFee)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RequestedTxHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RequestedLogIndex != 0 {
		n += 1 + sovTypes(uint64(m.RequestedLogIndex))
	}
	return n
}

func (m *ReadResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.ResultData)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ObservedBlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.ObservedBlockHeight))
	}
	l = len(m.ObservedBlockHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Aggregates) > 0 {
		for _, e := range m.Aggregates {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *AggregateValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExtractIndex != 0 {
		n += 1 + sovTypes(uint64(m.ExtractIndex))
	}
	if m.Mode != 0 {
		n += 1 + sovTypes(uint64(m.Mode))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *UniversalRead) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Request != nil {
		l = m.Request.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.BallotKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.PcTx) > 0 {
		for _, e := range m.PcTx {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReadRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = append(m.Query[:0], dAtA[iNdEx:postIndex]...)
			if m.Query == nil {
				m.Query = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinConfirmations", wireType)
			}
			m.MinConfirmations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinConfirmations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationBlockHeight", wireType)
			}
			m.DestinationBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryBlockHeight", wireType)
			}
			m.ExpiryBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtHeight", wireType)
			}
			m.CreatedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackTarget", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackTarget = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalFunder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginalFunder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeesDeposited", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeesDeposited = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestedTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedLogIndex", wireType)
			}
			m.RequestedLogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedLogIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ReadStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultData = append(m.ResultData[:0], dAtA[iNdEx:postIndex]...)
			if m.ResultData == nil {
				m.ResultData = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedBlockHeight", wireType)
			}
			m.ObservedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedBlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservedBlockHash = append(m.ObservedBlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ObservedBlockHash == nil {
				m.ObservedBlockHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aggregates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aggregates = append(m.Aggregates, &AggregateValue{})
			if err := m.Aggregates[len(m.Aggregates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AggregateValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AggregateValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AggregateValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtractIndex", wireType)
			}
			m.ExtractIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExtractIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UniversalRead) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UniversalRead: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UniversalRead: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Request == nil {
				m.Request = &ReadRequest{}
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &ReadResult{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= UniversalReadStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BallotKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BallotKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PcTx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PcTx = append(m.PcTx, &types.PCTx{})
			if err := m.PcTx[len(m.PcTx)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
