name: 'Setup dkls23-rs'
description: 'Configure Git/Cargo and clone dkls23-rs repository for building'

inputs:
  ci_token:
    description: 'CI token with access to dkls23-rs and garbling repositories'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Git and Cargo for private repos
      shell: bash
      env:
        CI_DKLS_GARBLING: ${{ inputs.ci_token }}
      run: |
        # Configure Git URL rewrite to include token for silence-laboratories repos
        git config --global url."https://${CI_DKLS_GARBLING}@github.com/silence-laboratories/".insteadOf "https://github.com/silence-laboratories/"
        git config --global url."https://github.com/".insteadOf "git@github.com:"

        # Also set up credential helper as fallback (for Cargo's git operations)
        git config --global credential.helper store
        echo "https://${CI_DKLS_GARBLING}@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials

        # Configure Cargo to use Git CLI for fetching dependencies
        mkdir -p ~/.cargo
        echo '[net]' >> ~/.cargo/config.toml
        echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml

        # Clone dkls23-rs repository (using fork until upstream is fixed)
        git clone --depth 1 https://${CI_DKLS_GARBLING}@github.com/mohammeds1992/dkls23-rs.git ../dkls23-rs

        # Clone garbling repository (using fork until upstream is fixed)
        git clone --depth 1 https://${CI_DKLS_GARBLING}@github.com/mohammeds1992/garbling.git ../garbling
