// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pushchain/push-chain-node/x/uexecutor/types (interfaces: UCallbackKeeper)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/cosmos/evm/x/vm/types"
	gomock "github.com/golang/mock/gomock"
)

// MockUCallbackKeeper is a mock of UCallbackKeeper interface.
type MockUCallbackKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockUCallbackKeeperMockRecorder
}

// MockUCallbackKeeperMockRecorder is the mock recorder for MockUCallbackKeeper.
type MockUCallbackKeeperMockRecorder struct {
	mock *MockUCallbackKeeper
}

// NewMockUCallbackKeeper creates a new mock instance.
func NewMockUCallbackKeeper(ctrl *gomock.Controller) *MockUCallbackKeeper {
	mock := &MockUCallbackKeeper{ctrl: ctrl}
	mock.recorder = &MockUCallbackKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUCallbackKeeper) EXPECT() *MockUCallbackKeeperMockRecorder {
	return m.recorder
}

// IngestReadRequests mocks base method.
func (m *MockUCallbackKeeper) IngestReadRequests(arg0 context.Context, arg1 *types.MsgEthereumTxResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestReadRequests", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestReadRequests indicates an expected call of IngestReadRequests.
func (mr *MockUCallbackKeeperMockRecorder) IngestReadRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestReadRequests", reflect.TypeOf((*MockUCallbackKeeper)(nil).IngestReadRequests), arg0, arg1)
}
