// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crosschain/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParams struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f25e0a13815164b, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f25e0a13815164b, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgFactoryAddress defines the Msg/FactoryAddress request type.
type MsgSetFactoryAddress struct {
	// admin is the account that is authorized to set the factory address.
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// factory_address is the address of the factory contract for smart account deployments.
	FactoryAddress string `protobuf:"bytes,2,opt,name=factory_address,json=factoryAddress,proto3" json:"factory_address,omitempty"`
}

func (m *MsgSetFactoryAddress) Reset()         { *m = MsgSetFactoryAddress{} }
func (m *MsgSetFactoryAddress) String() string { return proto.CompactTextString(m) }
func (*MsgSetFactoryAddress) ProtoMessage()    {}
func (*MsgSetFactoryAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f25e0a13815164b, []int{2}
}
func (m *MsgSetFactoryAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetFactoryAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetFactoryAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetFactoryAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetFactoryAddress.Merge(m, src)
}
func (m *MsgSetFactoryAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetFactoryAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetFactoryAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetFactoryAddress proto.InternalMessageInfo

func (m *MsgSetFactoryAddress) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgSetFactoryAddress) GetFactoryAddress() string {
	if m != nil {
		return m.FactoryAddress
	}
	return ""
}

type MsgSetFactoryAddressResponse struct {
}

func (m *MsgSetFactoryAddressResponse) Reset()         { *m = MsgSetFactoryAddressResponse{} }
func (m *MsgSetFactoryAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetFactoryAddressResponse) ProtoMessage()    {}
func (*MsgSetFactoryAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f25e0a13815164b, []int{3}
}
func (m *MsgSetFactoryAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetFactoryAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetFactoryAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetFactoryAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetFactoryAddressResponse.Merge(m, src)
}
func (m *MsgSetFactoryAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetFactoryAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetFactoryAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetFactoryAddressResponse proto.InternalMessageInfo

// MsgVerifierPrecompile defines the Msg/VerifierPrecompile request type.
type MsgSetVerifierPrecompile struct {
	// admin is the account that is authorized to set the verifier precompile.
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// verifier_precompile is the address of the verifier precompile for smart account deployments.
	VerifierPrecompile string `protobuf:"bytes,2,opt,name=verifier_precompile,json=verifierPrecompile,proto3" json:"verifier_precompile,omitempty"`
}

func (m *MsgSetVerifierPrecompile) Reset()         { *m = MsgSetVerifierPrecompile{} }
func (m *MsgSetVerifierPrecompile) String() string { return proto.CompactTextString(m) }
func (*MsgSetVerifierPrecompile) ProtoMessage()    {}
func (*MsgSetVerifierPrecompile) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f25e0a13815164b, []int{4}
}
func (m *MsgSetVerifierPrecompile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetVerifierPrecompile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetVerifierPrecompile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetVerifierPrecompile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetVerifierPrecompile.Merge(m, src)
}
func (m *MsgSetVerifierPrecompile) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetVerifierPrecompile) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetVerifierPrecompile.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetVerifierPrecompile proto.InternalMessageInfo

func (m *MsgSetVerifierPrecompile) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgSetVerifierPrecompile) GetVerifierPrecompile() string {
	if m != nil {
		return m.VerifierPrecompile
	}
	return ""
}

type MsgSetVerifierPrecompileResponse struct {
}

func (m *MsgSetVerifierPrecompileResponse) Reset()         { *m = MsgSetVerifierPrecompileResponse{} }
func (m *MsgSetVerifierPrecompileResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetVerifierPrecompileResponse) ProtoMessage()    {}
func (*MsgSetVerifierPrecompileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f25e0a13815164b, []int{5}
}
func (m *MsgSetVerifierPrecompileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetVerifierPrecompileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetVerifierPrecompileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetVerifierPrecompileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetVerifierPrecompileResponse.Merge(m, src)
}
func (m *MsgSetVerifierPrecompileResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetVerifierPrecompileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetVerifierPrecompileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetVerifierPrecompileResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "crosschain.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "crosschain.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSetFactoryAddress)(nil), "crosschain.v1.MsgSetFactoryAddress")
	proto.RegisterType((*MsgSetFactoryAddressResponse)(nil), "crosschain.v1.MsgSetFactoryAddressResponse")
	proto.RegisterType((*MsgSetVerifierPrecompile)(nil), "crosschain.v1.MsgSetVerifierPrecompile")
	proto.RegisterType((*MsgSetVerifierPrecompileResponse)(nil), "crosschain.v1.MsgSetVerifierPrecompileResponse")
}

func init() { proto.RegisterFile("crosschain/v1/tx.proto", fileDescriptor_0f25e0a13815164b) }

var fileDescriptor_0f25e0a13815164b = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x85, 0x56, 0xea, 0x03, 0x5a, 0x61, 0x52, 0x9a, 0x1a, 0x64, 0x22, 0x23, 0x41,
	0x55, 0x84, 0x4f, 0x6d, 0x25, 0x86, 0x6e, 0xcd, 0x80, 0xd4, 0x21, 0x52, 0x95, 0x8a, 0x0e, 0x2c,
	0x91, 0xeb, 0x5c, 0x2e, 0x27, 0xc5, 0x3e, 0x73, 0xef, 0x6a, 0x35, 0x1b, 0xe2, 0x03, 0x20, 0x16,
	0x3e, 0x00, 0xdf, 0xa0, 0x03, 0x33, 0x73, 0xc7, 0x8a, 0x89, 0x09, 0xa1, 0x64, 0xe8, 0xd7, 0x40,
	0xf1, 0x39, 0x09, 0x8e, 0x43, 0x9b, 0x6e, 0xe7, 0xfb, 0xff, 0xdf, 0xef, 0xfd, 0x4f, 0xcf, 0x0f,
	0x1e, 0x07, 0x4a, 0x22, 0x06, 0x1d, 0x5f, 0x44, 0x34, 0xd9, 0xa6, 0xfa, 0xcc, 0x8b, 0x95, 0xd4,
	0xd2, 0x7a, 0x30, 0xb9, 0xf7, 0x92, 0x6d, 0x7b, 0x3d, 0x90, 0x18, 0x4a, 0xa4, 0x21, 0xf2, 0xa1,
	0x2d, 0x44, 0x6e, 0x7c, 0xf6, 0x93, 0x7c, 0x3d, 0x67, 0x11, 0x43, 0x81, 0x99, 0x58, 0xe6, 0x92,
	0xcb, 0xf4, 0x48, 0x87, 0xa7, 0xec, 0x76, 0xc3, 0xb0, 0x9a, 0x46, 0x30, 0x1f, 0x46, 0x72, 0x3f,
	0x13, 0x58, 0xad, 0x23, 0x7f, 0x17, 0xb7, 0x7c, 0xcd, 0x0e, 0x7d, 0xe5, 0x87, 0x68, 0xbd, 0x81,
	0x65, 0xff, 0x54, 0x77, 0xa4, 0x12, 0xba, 0x57, 0x21, 0x55, 0xb2, 0xb9, 0x5c, 0xab, 0xfc, 0xfc,
	0xfe, 0xba, 0x9c, 0x15, 0xee, 0xb7, 0x5a, 0x8a, 0x21, 0x1e, 0x69, 0x25, 0x22, 0xde, 0x98, 0x58,
	0xad, 0x5d, 0x58, 0x8a, 0x53, 0x42, 0x65, 0xa1, 0x4a, 0x36, 0xef, 0xed, 0xac, 0x79, 0xb9, 0x27,
	0x79, 0x06, 0x5f, 0xbb, 0x7b, 0xf1, 0xfb, 0x59, 0xa9, 0x91, 0x59, 0xf7, 0x56, 0x3e, 0x5d, 0x9d,
	0x6f, 0x4d, 0x20, 0xee, 0x06, 0xac, 0x4f, 0xe5, 0x69, 0x30, 0x8c, 0x65, 0x84, 0xcc, 0xfd, 0x4a,
	0xa0, 0x5c, 0x47, 0x7e, 0xc4, 0xf4, 0x5b, 0x3f, 0xd0, 0x52, 0xf5, 0xb2, 0x24, 0x96, 0x07, 0x8b,
	0x7e, 0x2b, 0x14, 0xd1, 0x8d, 0x61, 0x8d, 0xcd, 0xda, 0x87, 0xd5, 0xb6, 0x21, 0x34, 0x7d, 0xa3,
	0xa7, 0x89, 0xaf, 0xab, 0x5c, 0x69, 0xe7, 0x5a, 0xee, 0xc1, 0x30, 0xb6, 0xc1, 0xb9, 0x0e, 0x3c,
	0x9d, 0x15, 0x6b, 0x9c, 0xfb, 0x1b, 0x81, 0x8a, 0x31, 0x1c, 0x33, 0x25, 0xda, 0x82, 0xa9, 0x43,
	0xc5, 0x02, 0x19, 0xc6, 0xa2, 0xcb, 0x6e, 0x9d, 0xfd, 0x00, 0x1e, 0x25, 0x19, 0xa5, 0x19, 0x8f,
	0x31, 0x37, 0xe6, 0xb7, 0x92, 0x42, 0xeb, 0xdc, 0x1b, 0x5c, 0xa8, 0xfe, 0x2f, 0xe2, 0xe8, 0x1d,
	0x3b, 0x3f, 0x16, 0xe0, 0x4e, 0x1d, 0xb9, 0x75, 0x0c, 0xf7, 0x73, 0xff, 0x8b, 0x33, 0x35, 0xe7,
	0xa9, 0xf9, 0xd9, 0x2f, 0xae, 0xd7, 0x47, 0x7c, 0x8b, 0xc1, 0xc3, 0xe2, 0x6c, 0x9f, 0x17, 0x8b,
	0x0b, 0x26, 0xfb, 0xd5, 0x1c, 0xa6, 0x71, 0x9b, 0x0f, 0xb0, 0x36, 0x7b, 0x14, 0x2f, 0x67, 0x52,
	0x8a, 0x46, 0x9b, 0xce, 0x69, 0x1c, 0xb5, 0xb4, 0x17, 0x3f, 0x5e, 0x9d, 0x6f, 0x91, 0xda, 0xc1,
	0x45, 0xdf, 0x21, 0x97, 0x7d, 0x87, 0xfc, 0xe9, 0x3b, 0xe4, 0xcb, 0xc0, 0x29, 0x5d, 0x0e, 0x9c,
	0xd2, 0xaf, 0x81, 0x53, 0x7a, 0x4f, 0xb9, 0xd0, 0x9d, 0xd3, 0x13, 0x2f, 0x90, 0x21, 0x55, 0xb2,
	0xdb, 0x4d, 0xd1, 0x48, 0x63, 0xb3, 0xe6, 0x67, 0xf4, 0x9f, 0x9d, 0xd7, 0xbd, 0x98, 0xe1, 0xc9,
	0x52, 0xba, 0xbe, 0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x14, 0x5a, 0xcd, 0x41, 0x4e, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the parameters.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// SetFactoryAddress defines a admin operation for setting the factory address.
	SetFactoryAddress(ctx context.Context, in *MsgSetFactoryAddress, opts ...grpc.CallOption) (*MsgSetFactoryAddressResponse, error)
	// SetVerifierPrecompile defines a admin operation for setting the verifier precompile.
	SetVerifierPrecompile(ctx context.Context, in *MsgSetVerifierPrecompile, opts ...grpc.CallOption) (*MsgSetVerifierPrecompileResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/crosschain.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetFactoryAddress(ctx context.Context, in *MsgSetFactoryAddress, opts ...grpc.CallOption) (*MsgSetFactoryAddressResponse, error) {
	out := new(MsgSetFactoryAddressResponse)
	err := c.cc.Invoke(ctx, "/crosschain.v1.Msg/SetFactoryAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetVerifierPrecompile(ctx context.Context, in *MsgSetVerifierPrecompile, opts ...grpc.CallOption) (*MsgSetVerifierPrecompileResponse, error) {
	out := new(MsgSetVerifierPrecompileResponse)
	err := c.cc.Invoke(ctx, "/crosschain.v1.Msg/SetVerifierPrecompile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the parameters.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// SetFactoryAddress defines a admin operation for setting the factory address.
	SetFactoryAddress(context.Context, *MsgSetFactoryAddress) (*MsgSetFactoryAddressResponse, error)
	// SetVerifierPrecompile defines a admin operation for setting the verifier precompile.
	SetVerifierPrecompile(context.Context, *MsgSetVerifierPrecompile) (*MsgSetVerifierPrecompileResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SetFactoryAddress(ctx context.Context, req *MsgSetFactoryAddress) (*MsgSetFactoryAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFactoryAddress not implemented")
}
func (*UnimplementedMsgServer) SetVerifierPrecompile(ctx context.Context, req *MsgSetVerifierPrecompile) (*MsgSetVerifierPrecompileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVerifierPrecompile not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crosschain.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetFactoryAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetFactoryAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetFactoryAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crosschain.v1.Msg/SetFactoryAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetFactoryAddress(ctx, req.(*MsgSetFactoryAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetVerifierPrecompile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetVerifierPrecompile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetVerifierPrecompile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crosschain.v1.Msg/SetVerifierPrecompile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetVerifierPrecompile(ctx, req.(*MsgSetVerifierPrecompile))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crosschain.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SetFactoryAddress",
			Handler:    _Msg_SetFactoryAddress_Handler,
		},
		{
			MethodName: "SetVerifierPrecompile",
			Handler:    _Msg_SetVerifierPrecompile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crosschain/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetFactoryAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetFactoryAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetFactoryAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FactoryAddress) > 0 {
		i -= len(m.FactoryAddress)
		copy(dAtA[i:], m.FactoryAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FactoryAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetFactoryAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetFactoryAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetFactoryAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetVerifierPrecompile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetVerifierPrecompile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetVerifierPrecompile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerifierPrecompile) > 0 {
		i -= len(m.VerifierPrecompile)
		copy(dAtA[i:], m.VerifierPrecompile)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerifierPrecompile)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetVerifierPrecompileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetVerifierPrecompileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetVerifierPrecompileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetFactoryAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FactoryAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetFactoryAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetVerifierPrecompile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VerifierPrecompile)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetVerifierPrecompileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetFactoryAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetFactoryAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetFactoryAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactoryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetFactoryAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetFactoryAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetFactoryAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetVerifierPrecompile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetVerifierPrecompile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetVerifierPrecompile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierPrecompile", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifierPrecompile = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetVerifierPrecompileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetVerifierPrecompileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetVerifierPrecompileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
