name: E2E Test Workflow

on:
  push:
    branches:
      - e2e-test
  pull_request:
    branches:
      - e2e-test
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
      
      - name: Ensure PATH includes Solana
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Check solana version
        run: solana --version
      
      - name: Start Solana Test Validator
        run: |
          solana-test-validator --reset --rpc-port 8899 --limit-ledger-size 50000000 --url https://api.devnet.solana.com \
            --clone ETGtqwDKEm1Z9gq6FdvYUfyDuUZr7g4UdPSmyNLVGriX \
            --clone 7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE &
      
      - name: Wait for validator to start
        run: sleep 10
      
      - name: Set Solana Keypair
        run: solana config set --keypair "$(pwd)/.github/Solana-key.json"

      - name: Run E2E Tests
        run: make e2e
        env:
          PATH: $HOME/.local/share/solana/install/active_release/bin:/usr/local/bin:/usr/bin:/bin
      
      - name: Stop Solana Test Validator
        run: pkill solana-test-validator || true
