name: E2E Test Workflow

on:
  push:
    branches:
      - e2e-test
  pull_request:
    branches:
      - e2e-test
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  PATH: $HOME/.local/share/solana/install/active_release/bin:/usr/local/bin:/usr/bin:/bin

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Solana CLI
      run: |
        curl -sSfL https://release.solana.com/v1.14.17/install | sh

    - name: List rustup toolchains
      run: rustup toolchain list

    - name: Set default toolchain to stable
      run: rustup default stable

    - name: Set Solana target cluster to local
      run: solana config set --url http://localhost:8899

    - name: Start Solana Test Validator
      run: |
        solana-test-validator --reset --rpc-port 8899 --limit-ledger-size 50000000 --url https://api.devnet.solana.com \
        --clone ETGtqwDKEm1Z9gq6FdvYUfyDuUZr7g4UdPSmyNLVGriX \
        --clone 7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE &

    - name: Wait for validator to start
      run: sleep 10

    - name: Set Solana Keypair Environment
      run: |
        export SOLANA_KEYPAIR="$(pwd)/.github/Solana-key.json"
        solana config set --keypair "$SOLANA_KEYPAIR"

    - name: Run E2E Tests
      run: make e2e

    - name: Stop Solana Test Validator
      run: pkill solana-test-validator || true
